/**
 * Created by linxiaojie on 2017/8/8.
 */

export const SET_USER = 'SET_USER'
export const SET_CODE = 'SET_CODE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_INTRODUCTION = 'SET_INTRODUCTION'
export const SET_SETTING = 'SET_SETTING'
export const SET_STATUS = 'SET_STATUS'
export const SET_LOGIN_NAME = 'SET_LOGIN_NAME'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_CURRENT_ROLES = 'SET_CURRENT_ROLES'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'


/*
* role 角色管理
* */
export const SET_ROLES_LIST = 'SET_ROLES_LIST'
export const SET_ROLES_SELECTED = 'SET_ROLES_SELECTED'
export const SET_ROLES_PERMISSIONS = 'SET_ROLE_PERMISSIONS'

/*
* 权限管理
* */
export const SET_PERMISSIONS_LIST = 'SET_PERMISSIONS_LIST'
export const SET_PERMISSIONS_SELECTED = 'SET_PERMISSIONS_SELECTED'
export const SET_PERMISSIONS_PERMISSIONS = 'SET_PERMISSION_PERMISSIONS'
